### ISSUE TITLE
excluding deprecated strings

### ISSUE THREAD

**Issue by brianteeman** [aDaneInSpain/Find-Unused-Joomla-Language-Constants#3]
We are looking at marking deprecated / unused strings in the core by preceding them with a comment.

Is it possible to make the script ignore (or flag) deprecated strings. 

Basically it should ignore any string that has a comment directly above it

*\* example **
TPL_BEEZ3_TEXTRIGHTOPEN="Open info"
TPL_BEEZ3_XML_DESCRIPTION="Accessible template for Joomla! Beez, the HTML 4 version."
; This string is not used and kept for B/C. Do not translate this string. 
TPL_BEEZ3_YOUR_SITE_DESCRIPTION="Your site description"

So TPL_BEEZ3_YOUR_SITE_DESCRIPTION would NOT be listed in the script output

**Comment by brianteeman** [comment]
BTW I was just shown this http://www.pages-and-items.com/extensions/language-file-tool

**Comment by aDaneInSpain** [comment]
That tool looks neat. Thanks for sharing. I will take a look at implementing what you said. I would recommend that we say in the comment includes the word 'deprecated' that it is then ignored?

**Comment by brianteeman** [comment]
Dont waste your time on it right now. A french person is currently blocking
any changes and i'm losing interest

On 23 January 2015 at 13:43, Søren Beck Jensen <notifications@github.com>
wrote:

> That tool looks neat. Thanks for sharing. I will take a look at
> implementing what you said. I would recommend that we say in the comment
> includes the word 'deprecated' that it is then ignored?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Jensen-Technologies/Find-Unused-Joomla-Language-Constants/issues/3#issuecomment-71194481>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by aDaneInSpain** [comment]
OK, got ya. Sorry to hear that.

>
